TKDemoMVC/src/TKDemoMVC/Controllers/CacheController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TKDemoMVC.Controllers
{
    public class CacheController:Controller
    {
        public IActionResult Index() {
            return View();
        }
    }
}

TKDemoMVC/src/TKDemoMVC/Controllers/DiRepositoryController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TKDemoMVC.Models;

namespace TKDemoMVC.Controllers
{
    public class DiRepositoryController: Controller {
        IRepository<Entity1> repository;

        ///Must be public property - do
        [FromServices]
        public IRepository<Entity1> repository1 {
            get; set;
        }

        public DiRepositoryController(RepositoryMem<Entity1> rep1,IRepository<Entity1> irep1) {
            rep1.Add(new Entity1() { Title = DateTime.Now.Ticks.ToString() }); //Singleton
            irep1.Add(new Entity1() { Title = DateTime.Now.Ticks.ToString() }); //Transient
            repository = rep1;
        }

        public IActionResult Index() {
            return View(repository.Get()); 
        }
    }
}

TKDemoMVC/src/TKDemoMVC/Controllers/OptionsController.cs
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.OptionsModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace TKDemoMVC.Controllers {
    public class Data123Config {
        public int Value1 { get; set; }
        public string Value2 { get; set; }
        public DefaultConnectionClass DefaultConnection { get; set; }
    }

    public class DefaultConnectionClass {
        public string ConnectionString { get; set; }
    }
    public class OptionsController : Controller {
        AppSettingsConfig Options { get; }
        Data123Config Data { get; }
        SecretsConfig Secrets { get; }
        public OptionsController(IOptions<AppSettingsConfig> opt, IOptions<Data123Config> dat, IOptions<SecretsConfig> sec) {
            Options = opt.Value;
            Data = dat.Value;
            //user-secret.cmd set AzureKey ABC
            Secrets = sec.Value;
        }
        public IActionResult Index() {
            return View(); //Maybe using model?
        }
    }
}

TKDemoMVC/src/TKDemoMVC/Controllers/TagHelperDemoController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TKDemoMVC.Controllers
{
    public class TagHelperDemoController: Controller {
        public IActionResult Index() {
            return View(); 
        }
    }
}

TKDemoMVC/src/TKDemoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - TKDemoMVC</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">TKDemoMVC</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                        <li><a asp-controller="Options" asp-action="Index">Options</a></li>
                        <li><a asp-controller="TK" asp-action="Index">TK</a></li>
                        <li><a asp-controller="DiRepository" asp-action="Index">DiRepository</a></li>
                        <li><a asp-controller="Cache" asp-action="Index">Cache</a></li>
                        <li><a asp-controller="TagHelperDemo" asp-action="Index">TagHelperDemo</a></li>
                        <li><a asp-controller="DemoViewComponents" asp-action="Index">DemoViewComponents</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - TKDemoMVC</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>